// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://glink.so/api/rest' | (string & {});
};

/**
 * Authorization not provided error (401)
 *
 * The error information
 */
export type ErrorUnauthorized = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

/**
 * Insufficient access error (403)
 *
 * The error information
 */
export type ErrorForbidden = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

/**
 * Internal server error error (500)
 *
 * The error information
 */
export type ErrorInternalServerError = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

/**
 * Invalid input data error (400)
 *
 * The error information
 */
export type ErrorBadRequest = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

/**
 * Not found error (404)
 *
 * The error information
 */
export type ErrorNotFound = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

export type UserGetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UserGetCurrentUserErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type UserGetCurrentUserError = UserGetCurrentUserErrors[keyof UserGetCurrentUserErrors];

export type UserGetCurrentUserResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UserGetPreferencesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/preferences';
};

export type UserGetPreferencesErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type UserGetPreferencesError = UserGetPreferencesErrors[keyof UserGetPreferencesErrors];

export type UserGetPreferencesResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UserGetSinglePreferenceData = {
    body: {
        key: 'notifications' | 'sound' | 'analytics' | 'emailMarketing' | 'emailUpdates' | 'aiProviderEnabledopenai' | 'aiProviderEnabledanthropic' | 'aiProviderEnabledxai' | 'aiProviderEnabledgemini' | 'aiProviderEnabledmistral' | 'aiProviderEnabledllama' | 'aiProviderEnabledcohere' | 'aiProviderEnabledperplexity' | 'aiProviderEnabledgroq' | 'aiProviderEnabledazure' | 'aiProviderEnabledamazon-bedrock' | 'aiProviderKeyopenai' | 'aiProviderKeyanthropic' | 'aiProviderKeyxai' | 'aiProviderKeygemini' | 'aiProviderKeymistral' | 'aiProviderKeyllama' | 'aiProviderKeycohere' | 'aiProviderKeyperplexity' | 'aiProviderKeygroq' | 'aiProviderKeyazure' | 'aiProviderKeyamazon-bedrock';
        defaultValue?: boolean | string;
    };
    path?: never;
    query?: never;
    url: '/users/preferences/get';
};

export type UserGetSinglePreferenceErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type UserGetSinglePreferenceError = UserGetSinglePreferenceErrors[keyof UserGetSinglePreferenceErrors];

export type UserGetSinglePreferenceResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UserUpdatePreferenceData = {
    body: {
        key: 'notifications' | 'sound' | 'analytics' | 'emailMarketing' | 'emailUpdates' | 'aiProviderEnabledopenai' | 'aiProviderEnabledanthropic' | 'aiProviderEnabledxai' | 'aiProviderEnabledgemini' | 'aiProviderEnabledmistral' | 'aiProviderEnabledllama' | 'aiProviderEnabledcohere' | 'aiProviderEnabledperplexity' | 'aiProviderEnabledgroq' | 'aiProviderEnabledazure' | 'aiProviderEnabledamazon-bedrock' | 'aiProviderKeyopenai' | 'aiProviderKeyanthropic' | 'aiProviderKeyxai' | 'aiProviderKeygemini' | 'aiProviderKeymistral' | 'aiProviderKeyllama' | 'aiProviderKeycohere' | 'aiProviderKeyperplexity' | 'aiProviderKeygroq' | 'aiProviderKeyazure' | 'aiProviderKeyamazon-bedrock';
        value: boolean | string | null;
    };
    path?: never;
    query?: never;
    url: '/users/preferences/update';
};

export type UserUpdatePreferenceErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type UserUpdatePreferenceError = UserUpdatePreferenceErrors[keyof UserUpdatePreferenceErrors];

export type UserUpdatePreferenceResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UserDisconnectAccountData = {
    body?: never;
    path?: never;
    query: {
        providerId: string;
    };
    url: '/users/disconnect-account';
};

export type UserDisconnectAccountErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type UserDisconnectAccountError = UserDisconnectAccountErrors[keyof UserDisconnectAccountErrors];

export type UserDisconnectAccountResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UserGetUserForEditingProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/profile/edit';
};

export type UserGetUserForEditingProfileErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type UserGetUserForEditingProfileError = UserGetUserForEditingProfileErrors[keyof UserGetUserForEditingProfileErrors];

export type UserGetUserForEditingProfileResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UserUpdateProfileData = {
    body: {
        name: string;
        username?: string;
        bio?: string;
        timezone?: string;
        avatarImageId?: string | null;
        coverImageId?: string | null;
        avatarImage?: {
            id: string;
            key: string;
        } | null;
        coverImage?: {
            id: string;
            key: string;
        } | null;
    };
    path?: never;
    query?: never;
    url: '/users/profile/update';
};

export type UserUpdateProfileErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type UserUpdateProfileError = UserUpdateProfileErrors[keyof UserUpdateProfileErrors];

export type UserUpdateProfileResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UserMarkUserAsOnboardedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/onboarding/mark';
};

export type UserMarkUserAsOnboardedErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type UserMarkUserAsOnboardedError = UserMarkUserAsOnboardedErrors[keyof UserMarkUserAsOnboardedErrors];

export type UserMarkUserAsOnboardedResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UserResetUserOnboardingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/onboarding/reset';
};

export type UserResetUserOnboardingErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type UserResetUserOnboardingError = UserResetUserOnboardingErrors[keyof UserResetUserOnboardingErrors];

export type UserResetUserOnboardingResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UserGetPublicProfileData = {
    body: {
        username: string;
    };
    path?: never;
    query?: never;
    url: '/users/public/profile';
};

export type UserGetPublicProfileErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type UserGetPublicProfileError = UserGetPublicProfileErrors[keyof UserGetPublicProfileErrors];

export type UserGetPublicProfileResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UserGetMyProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/profile/me';
};

export type UserGetMyProfileErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type UserGetMyProfileError = UserGetMyProfileErrors[keyof UserGetMyProfileErrors];

export type UserGetMyProfileResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type UtImageDeleteData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/ut-images/delete';
};

export type UtImageDeleteErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type UtImageDeleteError = UtImageDeleteErrors[keyof UtImageDeleteErrors];

export type UtImageDeleteResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type S3ImageGetByEntryIdData = {
    body: {
        entryId: string;
    };
    path?: never;
    query?: never;
    url: '/s3-images/by-entry';
};

export type S3ImageGetByEntryIdErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type S3ImageGetByEntryIdError = S3ImageGetByEntryIdErrors[keyof S3ImageGetByEntryIdErrors];

export type S3ImageGetByEntryIdResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type S3ImageDeleteData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/s3-images/delete';
};

export type S3ImageDeleteErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type S3ImageDeleteError = S3ImageDeleteErrors[keyof S3ImageDeleteErrors];

export type S3ImageDeleteResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type S3ImageGetUploadUrlData = {
    body: {
        fileName: string;
        contentType: string;
    };
    path?: never;
    query?: never;
    url: '/s3-images/upload-url';
};

export type S3ImageGetUploadUrlErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type S3ImageGetUploadUrlError = S3ImageGetUploadUrlErrors[keyof S3ImageGetUploadUrlErrors];

export type S3ImageGetUploadUrlResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type PolarGetBillingStateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/polar/billing-state';
};

export type PolarGetBillingStateErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type PolarGetBillingStateError = PolarGetBillingStateErrors[keyof PolarGetBillingStateErrors];

export type PolarGetBillingStateResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type AuthChangePasswordData = {
    body: {
        currentPassword: string;
        newPassword: string;
        confirmPassword: string;
    };
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type AuthChangePasswordErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type AuthChangePasswordError = AuthChangePasswordErrors[keyof AuthChangePasswordErrors];

export type AuthChangePasswordResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ProjectCreateData = {
    body: {
        name: string;
        description?: string;
        emoji?: string;
        contentType?: 'Changelogs' | 'Entries' | 'Both';
        githubRepoUrl?: string | '';
    };
    path?: never;
    query?: never;
    url: '/projects';
};

export type ProjectCreateErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ProjectCreateError = ProjectCreateErrors[keyof ProjectCreateErrors];

export type ProjectCreateResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ProjectGetByIdData = {
    body: {
        id: string;
    };
    path?: never;
    query?: never;
    url: '/projects/get';
};

export type ProjectGetByIdErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ProjectGetByIdError = ProjectGetByIdErrors[keyof ProjectGetByIdErrors];

export type ProjectGetByIdResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ProjectGetPublicProjectData = {
    body: {
        username: string;
        projectSlug: string;
    };
    path?: never;
    query?: never;
    url: '/projects/public/get';
};

export type ProjectGetPublicProjectErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ProjectGetPublicProjectError = ProjectGetPublicProjectErrors[keyof ProjectGetPublicProjectErrors];

export type ProjectGetPublicProjectResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ProjectGetGitHubYearlyActivityData = {
    body: {
        username: string;
        projectSlug: string;
    };
    path?: never;
    query?: never;
    url: '/projects/public/github/yearly';
};

export type ProjectGetGitHubYearlyActivityErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ProjectGetGitHubYearlyActivityError = ProjectGetGitHubYearlyActivityErrors[keyof ProjectGetGitHubYearlyActivityErrors];

export type ProjectGetGitHubYearlyActivityResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ProjectGetPublicChangelogsData = {
    body: {
        username: string;
        projectSlug: string;
        limit?: number;
        cursor?: number;
    };
    path?: never;
    query?: never;
    url: '/projects/public/changelogs';
};

export type ProjectGetPublicChangelogsErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ProjectGetPublicChangelogsError = ProjectGetPublicChangelogsErrors[keyof ProjectGetPublicChangelogsErrors];

export type ProjectGetPublicChangelogsResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ProjectGetPublicEntriesData = {
    body: {
        username: string;
        projectSlug: string;
        limit?: number;
    };
    path?: never;
    query?: never;
    url: '/projects/public/entries';
};

export type ProjectGetPublicEntriesErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ProjectGetPublicEntriesError = ProjectGetPublicEntriesErrors[keyof ProjectGetPublicEntriesErrors];

export type ProjectGetPublicEntriesResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ProjectGetPublicEntryData = {
    body: {
        username: string;
        projectSlug: string;
        entrySlug: string;
    };
    path?: never;
    query?: never;
    url: '/projects/public/entry';
};

export type ProjectGetPublicEntryErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ProjectGetPublicEntryError = ProjectGetPublicEntryErrors[keyof ProjectGetPublicEntryErrors];

export type ProjectGetPublicEntryResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ProjectGetPublicChangelogData = {
    body: {
        username: string;
        projectSlug: string;
        changelogSlug: string;
        preview?: boolean;
    };
    path?: never;
    query?: never;
    url: '/projects/public/changelog';
};

export type ProjectGetPublicChangelogErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ProjectGetPublicChangelogError = ProjectGetPublicChangelogErrors[keyof ProjectGetPublicChangelogErrors];

export type ProjectGetPublicChangelogResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ProjectListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects/list';
};

export type ProjectListErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ProjectListError = ProjectListErrors[keyof ProjectListErrors];

export type ProjectListResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ProjectUpdateData = {
    body: {
        id: string;
        name?: string;
        description?: string;
        emoji?: string;
        contentType?: 'Changelogs' | 'Entries' | 'Both';
        githubRepoUrl?: string | '';
    };
    path?: never;
    query?: never;
    url: '/projects/update';
};

export type ProjectUpdateErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ProjectUpdateError = ProjectUpdateErrors[keyof ProjectUpdateErrors];

export type ProjectUpdateResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ProjectDeleteData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/projects/delete';
};

export type ProjectDeleteErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ProjectDeleteError = ProjectDeleteErrors[keyof ProjectDeleteErrors];

export type ProjectDeleteResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ProjectGetPublicChangelogByVersionData = {
    body: {
        username: string;
        projectSlug: string;
        version: string;
    };
    path?: never;
    query?: never;
    url: '/projects/public/changelog/version';
};

export type ProjectGetPublicChangelogByVersionErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ProjectGetPublicChangelogByVersionError = ProjectGetPublicChangelogByVersionErrors[keyof ProjectGetPublicChangelogByVersionErrors];

export type ProjectGetPublicChangelogByVersionResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ProjectGetChangelogsInVersionRangeData = {
    body: {
        username: string;
        projectSlug: string;
        versionFrom: string;
        versionTo: string;
    };
    path?: never;
    query?: never;
    url: '/projects/public/changelogs/range';
};

export type ProjectGetChangelogsInVersionRangeErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ProjectGetChangelogsInVersionRangeError = ProjectGetChangelogsInVersionRangeErrors[keyof ProjectGetChangelogsInVersionRangeErrors];

export type ProjectGetChangelogsInVersionRangeResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type EntryCreateData = {
    body: {
        title?: string;
        description?: string;
        type?: string;
        projectId: string;
    };
    path?: never;
    query?: never;
    url: '/entries';
};

export type EntryCreateErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type EntryCreateError = EntryCreateErrors[keyof EntryCreateErrors];

export type EntryCreateResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type EntryGetByIdData = {
    body: {
        id: string;
    };
    path?: never;
    query?: never;
    url: '/entries/get';
};

export type EntryGetByIdErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type EntryGetByIdError = EntryGetByIdErrors[keyof EntryGetByIdErrors];

export type EntryGetByIdResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type EntryListData = {
    body: {
        projectId: string;
    };
    path?: never;
    query?: never;
    url: '/entries/list';
};

export type EntryListErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type EntryListError = EntryListErrors[keyof EntryListErrors];

export type EntryListResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type EntryUpdateStatusData = {
    body: {
        id: string;
        status: 'Draft' | 'ReadyForReview' | 'Published';
    };
    path?: never;
    query?: never;
    url: '/entries/update-status';
};

export type EntryUpdateStatusErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type EntryUpdateStatusError = EntryUpdateStatusErrors[keyof EntryUpdateStatusErrors];

export type EntryUpdateStatusResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type EntryListByProjectData = {
    body: {
        projectId: string;
    };
    path?: never;
    query?: never;
    url: '/entries/list-by-project';
};

export type EntryListByProjectErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type EntryListByProjectError = EntryListByProjectErrors[keyof EntryListByProjectErrors];

export type EntryListByProjectResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type EntryUpdateData = {
    body: {
        id: string;
        title?: string;
        description?: string;
        type?: string;
        emoji?: string;
        slug?: string;
    };
    path?: never;
    query?: never;
    url: '/entries/update';
};

export type EntryUpdateErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type EntryUpdateError = EntryUpdateErrors[keyof EntryUpdateErrors];

export type EntryUpdateResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type EntryCheckSlugAvailabilityData = {
    body: {
        slug: string;
        projectId: string;
        entryId?: string;
    };
    path?: never;
    query?: never;
    url: '/entries/check-slug';
};

export type EntryCheckSlugAvailabilityErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type EntryCheckSlugAvailabilityError = EntryCheckSlugAvailabilityErrors[keyof EntryCheckSlugAvailabilityErrors];

export type EntryCheckSlugAvailabilityResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type EntryDeleteData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/entries/delete';
};

export type EntryDeleteErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type EntryDeleteError = EntryDeleteErrors[keyof EntryDeleteErrors];

export type EntryDeleteResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type EntryReorderEntriesData = {
    body: {
        projectId: string;
        entryIds: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/entries/reorder';
};

export type EntryReorderEntriesErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type EntryReorderEntriesError = EntryReorderEntriesErrors[keyof EntryReorderEntriesErrors];

export type EntryReorderEntriesResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type EntryGetPublicTimelineData = {
    body: {
        limit?: number;
        cursor?: string;
    };
    path?: never;
    query?: never;
    url: '/entries/public/timeline';
};

export type EntryGetPublicTimelineErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type EntryGetPublicTimelineError = EntryGetPublicTimelineErrors[keyof EntryGetPublicTimelineErrors];

export type EntryGetPublicTimelineResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type EntryGetLeaderboardData = {
    body: {
        limit?: number;
    };
    path?: never;
    query?: never;
    url: '/entries/public/leaderboard';
};

export type EntryGetLeaderboardErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type EntryGetLeaderboardError = EntryGetLeaderboardErrors[keyof EntryGetLeaderboardErrors];

export type EntryGetLeaderboardResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type EntryGetTrendingProjectsData = {
    body: {
        limit?: number;
    };
    path?: never;
    query?: never;
    url: '/entries/public/trending-projects';
};

export type EntryGetTrendingProjectsErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type EntryGetTrendingProjectsError = EntryGetTrendingProjectsErrors[keyof EntryGetTrendingProjectsErrors];

export type EntryGetTrendingProjectsResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type EntryGetEntriesByDateData = {
    body: {
        username: string;
        date: string;
    };
    path?: never;
    query?: never;
    url: '/entries/public/by-date';
};

export type EntryGetEntriesByDateErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type EntryGetEntriesByDateError = EntryGetEntriesByDateErrors[keyof EntryGetEntriesByDateErrors];

export type EntryGetEntriesByDateResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type EntryGetTimelineActivityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/entries/public/timeline-activity';
};

export type EntryGetTimelineActivityErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type EntryGetTimelineActivityError = EntryGetTimelineActivityErrors[keyof EntryGetTimelineActivityErrors];

export type EntryGetTimelineActivityResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogCreateData = {
    body: {
        title: string;
        projectId: string;
    };
    path?: never;
    query?: never;
    url: '/changelogs';
};

export type ChangelogCreateErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogCreateError = ChangelogCreateErrors[keyof ChangelogCreateErrors];

export type ChangelogCreateResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogGetByIdData = {
    body: {
        id: string;
    };
    path?: never;
    query?: never;
    url: '/changelogs/get';
};

export type ChangelogGetByIdErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogGetByIdError = ChangelogGetByIdErrors[keyof ChangelogGetByIdErrors];

export type ChangelogGetByIdResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogListByProjectData = {
    body: {
        projectId: string;
    };
    path?: never;
    query?: never;
    url: '/changelogs/list';
};

export type ChangelogListByProjectErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogListByProjectError = ChangelogListByProjectErrors[keyof ChangelogListByProjectErrors];

export type ChangelogListByProjectResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogUpdateData = {
    body: {
        id: string;
        title: string;
        header?: string;
        footer?: string;
        version?: string;
    };
    path?: never;
    query?: never;
    url: '/changelogs/update';
};

export type ChangelogUpdateErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogUpdateError = ChangelogUpdateErrors[keyof ChangelogUpdateErrors];

export type ChangelogUpdateResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogUpdateStatusData = {
    body: {
        id: string;
        status: string;
    };
    path?: never;
    query?: never;
    url: '/changelogs/update-status';
};

export type ChangelogUpdateStatusErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogUpdateStatusError = ChangelogUpdateStatusErrors[keyof ChangelogUpdateStatusErrors];

export type ChangelogUpdateStatusResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogGetEntriesAndRequestsData = {
    body: {
        changelogId: string;
    };
    path?: never;
    query?: never;
    url: '/changelogs/entries-requests';
};

export type ChangelogGetEntriesAndRequestsErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogGetEntriesAndRequestsError = ChangelogGetEntriesAndRequestsErrors[keyof ChangelogGetEntriesAndRequestsErrors];

export type ChangelogGetEntriesAndRequestsResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogPublishData = {
    body: {
        id: string;
        publishedAt: string;
        shouldMoveEntries: boolean;
        shouldCloseRequests: boolean;
        shouldNotifyUsers: boolean;
        entriesColumnId?: string;
    };
    path?: never;
    query?: never;
    url: '/changelogs/publish';
};

export type ChangelogPublishErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogPublishError = ChangelogPublishErrors[keyof ChangelogPublishErrors];

export type ChangelogPublishResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogDeleteData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/changelogs/delete';
};

export type ChangelogDeleteErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogDeleteError = ChangelogDeleteErrors[keyof ChangelogDeleteErrors];

export type ChangelogDeleteResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogAddEntryData = {
    body: {
        changelogId: string;
        entryId: string;
        position?: string;
    };
    path?: never;
    query?: never;
    url: '/changelogs/entries/add';
};

export type ChangelogAddEntryErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogAddEntryError = ChangelogAddEntryErrors[keyof ChangelogAddEntryErrors];

export type ChangelogAddEntryResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogRemoveEntryData = {
    body: {
        entryId: string;
    };
    path?: never;
    query?: never;
    url: '/changelogs/entries/remove';
};

export type ChangelogRemoveEntryErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogRemoveEntryError = ChangelogRemoveEntryErrors[keyof ChangelogRemoveEntryErrors];

export type ChangelogRemoveEntryResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogReorderEntriesData = {
    body: {
        changelogId: string;
        entryIds: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/changelogs/entries/reorder';
};

export type ChangelogReorderEntriesErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogReorderEntriesError = ChangelogReorderEntriesErrors[keyof ChangelogReorderEntriesErrors];

export type ChangelogReorderEntriesResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogGetUnassignedEntriesData = {
    body: {
        projectId: string;
    };
    path?: never;
    query?: never;
    url: '/changelogs/entries/unassigned';
};

export type ChangelogGetUnassignedEntriesErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogGetUnassignedEntriesError = ChangelogGetUnassignedEntriesErrors[keyof ChangelogGetUnassignedEntriesErrors];

export type ChangelogGetUnassignedEntriesResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogGenerateMarkdownData = {
    body: {
        id: string;
    };
    path?: never;
    query?: never;
    url: '/changelogs/markdown';
};

export type ChangelogGenerateMarkdownErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogGenerateMarkdownError = ChangelogGenerateMarkdownErrors[keyof ChangelogGenerateMarkdownErrors];

export type ChangelogGenerateMarkdownResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogCreateChangeData = {
    body: {
        changelogId: string;
        title: string;
        tag: 'Feature' | 'BugFix' | 'Improvement';
    };
    path?: never;
    query?: never;
    url: '/changelogs/changes';
};

export type ChangelogCreateChangeErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogCreateChangeError = ChangelogCreateChangeErrors[keyof ChangelogCreateChangeErrors];

export type ChangelogCreateChangeResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogDeleteChangeData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/changelogs/changes/delete';
};

export type ChangelogDeleteChangeErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogDeleteChangeError = ChangelogDeleteChangeErrors[keyof ChangelogDeleteChangeErrors];

export type ChangelogDeleteChangeResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type ChangelogUpdateChangeData = {
    body: {
        id: string;
        title: string;
        tag: 'Feature' | 'BugFix' | 'Improvement';
    };
    path?: never;
    query?: never;
    url: '/changelogs/changes/update';
};

export type ChangelogUpdateChangeErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type ChangelogUpdateChangeError = ChangelogUpdateChangeErrors[keyof ChangelogUpdateChangeErrors];

export type ChangelogUpdateChangeResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type RequestGetPublicRequestsData = {
    body: {
        username: string;
        projectSlug: string;
        limit?: number;
    };
    path?: never;
    query?: never;
    url: '/requests/public/list';
};

export type RequestGetPublicRequestsErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type RequestGetPublicRequestsError = RequestGetPublicRequestsErrors[keyof RequestGetPublicRequestsErrors];

export type RequestGetPublicRequestsResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type RequestGetPublicRequestCategoriesData = {
    body: {
        username: string;
        projectSlug: string;
    };
    path?: never;
    query?: never;
    url: '/requests/public/categories';
};

export type RequestGetPublicRequestCategoriesErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type RequestGetPublicRequestCategoriesError = RequestGetPublicRequestCategoriesErrors[keyof RequestGetPublicRequestCategoriesErrors];

export type RequestGetPublicRequestCategoriesResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type RequestGetSizzyEmailData = {
    body: {
        activationId: string;
    };
    path?: never;
    query?: never;
    url: '/requests/public/sizzy-email';
};

export type RequestGetSizzyEmailErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type RequestGetSizzyEmailError = RequestGetSizzyEmailErrors[keyof RequestGetSizzyEmailErrors];

export type RequestGetSizzyEmailResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type RequestGetPublicRequestData = {
    body: {
        requestId: string;
        username: string;
        projectSlug: string;
    };
    path?: never;
    query?: never;
    url: '/requests/public/get';
};

export type RequestGetPublicRequestErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type RequestGetPublicRequestError = RequestGetPublicRequestErrors[keyof RequestGetPublicRequestErrors];

export type RequestGetPublicRequestResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type RequestCreatePublicRequestData = {
    body: {
        username: string;
        projectSlug: string;
        data: {
            title: string;
            content: string;
            categoryId?: string;
            imageIds?: Array<string>;
        };
        guestEmail?: string;
        activationId?: string;
        token?: string;
    };
    path?: never;
    query?: never;
    url: '/requests';
};

export type RequestCreatePublicRequestErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type RequestCreatePublicRequestError = RequestCreatePublicRequestErrors[keyof RequestCreatePublicRequestErrors];

export type RequestCreatePublicRequestResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type RequestCreateCommentData = {
    body: {
        requestId: string;
        text: string;
        imageIds?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/requests/comment';
};

export type RequestCreateCommentErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type RequestCreateCommentError = RequestCreateCommentErrors[keyof RequestCreateCommentErrors];

export type RequestCreateCommentResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type RequestApproveRequestData = {
    body: {
        requestId: string;
        username: string;
        projectSlug: string;
    };
    path?: never;
    query?: never;
    url: '/requests/approve';
};

export type RequestApproveRequestErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type RequestApproveRequestError = RequestApproveRequestErrors[keyof RequestApproveRequestErrors];

export type RequestApproveRequestResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type RequestToggleCloseRequestData = {
    body: {
        requestId: string;
        username: string;
        projectSlug: string;
    };
    path?: never;
    query?: never;
    url: '/requests/toggle-close';
};

export type RequestToggleCloseRequestErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type RequestToggleCloseRequestError = RequestToggleCloseRequestErrors[keyof RequestToggleCloseRequestErrors];

export type RequestToggleCloseRequestResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type RequestToggleLockRequestData = {
    body: {
        requestId: string;
        username: string;
        projectSlug: string;
    };
    path?: never;
    query?: never;
    url: '/requests/toggle-lock';
};

export type RequestToggleLockRequestErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type RequestToggleLockRequestError = RequestToggleLockRequestErrors[keyof RequestToggleLockRequestErrors];

export type RequestToggleLockRequestResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type RequestDeleteRequestData = {
    body?: never;
    path?: never;
    query: {
        requestId: string;
        username: string;
        projectSlug: string;
    };
    url: '/requests/delete';
};

export type RequestDeleteRequestErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type RequestDeleteRequestError = RequestDeleteRequestErrors[keyof RequestDeleteRequestErrors];

export type RequestDeleteRequestResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type RoadmapGetPublicRoadmapEntriesData = {
    body: {
        username: string;
        projectSlug: string;
        limit?: number;
    };
    path?: never;
    query?: never;
    url: '/roadmap/public/entries';
};

export type RoadmapGetPublicRoadmapEntriesErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type RoadmapGetPublicRoadmapEntriesError = RoadmapGetPublicRoadmapEntriesErrors[keyof RoadmapGetPublicRoadmapEntriesErrors];

export type RoadmapGetPublicRoadmapEntriesResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type RoadmapGetPublicRoadmapStatusesData = {
    body: {
        username: string;
        projectSlug: string;
    };
    path?: never;
    query?: never;
    url: '/roadmap/public/statuses';
};

export type RoadmapGetPublicRoadmapStatusesErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type RoadmapGetPublicRoadmapStatusesError = RoadmapGetPublicRoadmapStatusesErrors[keyof RoadmapGetPublicRoadmapStatusesErrors];

export type RoadmapGetPublicRoadmapStatusesResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type RoadmapGetRoadmapStatusesData = {
    body: {
        projectId: string;
    };
    path?: never;
    query?: never;
    url: '/roadmap/statuses';
};

export type RoadmapGetRoadmapStatusesErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type RoadmapGetRoadmapStatusesError = RoadmapGetRoadmapStatusesErrors[keyof RoadmapGetRoadmapStatusesErrors];

export type RoadmapGetRoadmapStatusesResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type FeatureGetPublicFeaturesData = {
    body: {
        username: string;
        projectSlug: string;
        limit?: number;
    };
    path?: never;
    query?: never;
    url: '/features/public/list';
};

export type FeatureGetPublicFeaturesErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type FeatureGetPublicFeaturesError = FeatureGetPublicFeaturesErrors[keyof FeatureGetPublicFeaturesErrors];

export type FeatureGetPublicFeaturesResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type FeatureGetPublicFeatureData = {
    body: {
        username: string;
        projectSlug: string;
        featureSlug: string;
    };
    path?: never;
    query?: never;
    url: '/features/public/get';
};

export type FeatureGetPublicFeatureErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type FeatureGetPublicFeatureError = FeatureGetPublicFeatureErrors[keyof FeatureGetPublicFeatureErrors];

export type FeatureGetPublicFeatureResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionGetCategoriesData = {
    body: {
        projectId: string;
    };
    path?: never;
    query?: never;
    url: '/discussions/categories';
};

export type DiscussionGetCategoriesErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionGetCategoriesError = DiscussionGetCategoriesErrors[keyof DiscussionGetCategoriesErrors];

export type DiscussionGetCategoriesResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionGetCategoriesByProjectSlugData = {
    body: {
        username: string;
        projectSlug: string;
    };
    path?: never;
    query?: never;
    url: '/discussions/categories/by-project';
};

export type DiscussionGetCategoriesByProjectSlugErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionGetCategoriesByProjectSlugError = DiscussionGetCategoriesByProjectSlugErrors[keyof DiscussionGetCategoriesByProjectSlugErrors];

export type DiscussionGetCategoriesByProjectSlugResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionCreateCategoryData = {
    body: {
        projectId: string;
        title: string;
        slug: string;
        emoji: string;
        color?: string | null;
        canBeAnswered?: boolean;
    };
    path?: never;
    query?: never;
    url: '/discussions/categories/create';
};

export type DiscussionCreateCategoryErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionCreateCategoryError = DiscussionCreateCategoryErrors[keyof DiscussionCreateCategoryErrors];

export type DiscussionCreateCategoryResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionUpdateCategoryData = {
    body: {
        id: string;
        title?: string;
        slug?: string;
        emoji?: string;
        color?: string | null;
        canBeAnswered?: boolean;
    };
    path?: never;
    query?: never;
    url: '/discussions/categories/update';
};

export type DiscussionUpdateCategoryErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionUpdateCategoryError = DiscussionUpdateCategoryErrors[keyof DiscussionUpdateCategoryErrors];

export type DiscussionUpdateCategoryResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionDeleteCategoryData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/discussions/categories/delete';
};

export type DiscussionDeleteCategoryErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionDeleteCategoryError = DiscussionDeleteCategoryErrors[keyof DiscussionDeleteCategoryErrors];

export type DiscussionDeleteCategoryResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionGetDiscussionsData = {
    body: {
        projectId: string;
        categorySlug?: string;
    };
    path?: never;
    query?: never;
    url: '/discussions/list';
};

export type DiscussionGetDiscussionsErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionGetDiscussionsError = DiscussionGetDiscussionsErrors[keyof DiscussionGetDiscussionsErrors];

export type DiscussionGetDiscussionsResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionGetDiscussionData = {
    body: {
        discussionId: string;
    };
    path?: never;
    query?: never;
    url: '/discussions/get';
};

export type DiscussionGetDiscussionErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionGetDiscussionError = DiscussionGetDiscussionErrors[keyof DiscussionGetDiscussionErrors];

export type DiscussionGetDiscussionResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionCreateDiscussionData = {
    body: {
        projectId: string;
        data: {
            title: string;
            body: string;
            categorySlug: string;
            sendUiNotification?: boolean;
            sendEmailNotification?: boolean;
            notificationMessage?: string;
        };
        images?: Array<{
            id: string;
        }>;
    };
    path?: never;
    query?: never;
    url: '/discussions/create';
};

export type DiscussionCreateDiscussionErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionCreateDiscussionError = DiscussionCreateDiscussionErrors[keyof DiscussionCreateDiscussionErrors];

export type DiscussionCreateDiscussionResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionUpdateDiscussionData = {
    body: {
        id: string;
        title?: string;
        body?: string;
        categorySlug?: string;
    };
    path?: never;
    query?: never;
    url: '/discussions/update';
};

export type DiscussionUpdateDiscussionErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionUpdateDiscussionError = DiscussionUpdateDiscussionErrors[keyof DiscussionUpdateDiscussionErrors];

export type DiscussionUpdateDiscussionResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionDeleteDiscussionData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/discussions/delete';
};

export type DiscussionDeleteDiscussionErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionDeleteDiscussionError = DiscussionDeleteDiscussionErrors[keyof DiscussionDeleteDiscussionErrors];

export type DiscussionDeleteDiscussionResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionPinDiscussionData = {
    body: {
        discussionId: string;
    };
    path?: never;
    query?: never;
    url: '/discussions/pin';
};

export type DiscussionPinDiscussionErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionPinDiscussionError = DiscussionPinDiscussionErrors[keyof DiscussionPinDiscussionErrors];

export type DiscussionPinDiscussionResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionWatchDiscussionData = {
    body: {
        discussionId: string;
    };
    path?: never;
    query?: never;
    url: '/discussions/watch';
};

export type DiscussionWatchDiscussionErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionWatchDiscussionError = DiscussionWatchDiscussionErrors[keyof DiscussionWatchDiscussionErrors];

export type DiscussionWatchDiscussionResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionIsWatchingDiscussionData = {
    body: {
        discussionId: string;
    };
    path?: never;
    query?: never;
    url: '/discussions/watch/status';
};

export type DiscussionIsWatchingDiscussionErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionIsWatchingDiscussionError = DiscussionIsWatchingDiscussionErrors[keyof DiscussionIsWatchingDiscussionErrors];

export type DiscussionIsWatchingDiscussionResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionReplyToDiscussionData = {
    body: {
        discussionId: string;
        body: string;
        images?: Array<{
            id: string;
        }>;
        replyToId?: string;
    };
    path?: never;
    query?: never;
    url: '/discussions/reply';
};

export type DiscussionReplyToDiscussionErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionReplyToDiscussionError = DiscussionReplyToDiscussionErrors[keyof DiscussionReplyToDiscussionErrors];

export type DiscussionReplyToDiscussionResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionUpdatePostData = {
    body: {
        id: string;
        body: string;
    };
    path?: never;
    query?: never;
    url: '/discussions/posts/update';
};

export type DiscussionUpdatePostErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionUpdatePostError = DiscussionUpdatePostErrors[keyof DiscussionUpdatePostErrors];

export type DiscussionUpdatePostResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionDeletePostData = {
    body?: never;
    path?: never;
    query: {
        id: string;
    };
    url: '/discussions/posts/delete';
};

export type DiscussionDeletePostErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionDeletePostError = DiscussionDeletePostErrors[keyof DiscussionDeletePostErrors];

export type DiscussionDeletePostResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionMarkAsAnswerData = {
    body: {
        postId: string;
    };
    path?: never;
    query?: never;
    url: '/discussions/answer/mark';
};

export type DiscussionMarkAsAnswerErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionMarkAsAnswerError = DiscussionMarkAsAnswerErrors[keyof DiscussionMarkAsAnswerErrors];

export type DiscussionMarkAsAnswerResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionUnmarkAsAnswerData = {
    body: {
        postId: string;
    };
    path?: never;
    query?: never;
    url: '/discussions/answer/unmark';
};

export type DiscussionUnmarkAsAnswerErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Not found
     */
    404: ErrorNotFound;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionUnmarkAsAnswerError = DiscussionUnmarkAsAnswerErrors[keyof DiscussionUnmarkAsAnswerErrors];

export type DiscussionUnmarkAsAnswerResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionReactData = {
    body: {
        discussionId?: string;
        discussionPostId?: string;
        type: 'THUMBS_UP' | 'THUMBS_DOWN' | 'LAUGH' | 'HOORAY' | 'CONFUSED' | 'HEART' | 'ROCKET' | 'EYES';
    };
    path?: never;
    query?: never;
    url: '/discussions/reactions';
};

export type DiscussionReactErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionReactError = DiscussionReactErrors[keyof DiscussionReactErrors];

export type DiscussionReactResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionGetReactionsData = {
    body: {
        discussionId?: string;
        discussionPostId?: string;
    };
    path?: never;
    query?: never;
    url: '/discussions/reactions/list';
};

export type DiscussionGetReactionsErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionGetReactionsError = DiscussionGetReactionsErrors[keyof DiscussionGetReactionsErrors];

export type DiscussionGetReactionsResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type DiscussionUpvoteData = {
    body: {
        discussionId?: string;
        discussionPostId?: string;
    };
    path?: never;
    query?: never;
    url: '/discussions/upvote';
};

export type DiscussionUpvoteErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type DiscussionUpvoteError = DiscussionUpvoteErrors[keyof DiscussionUpvoteErrors];

export type DiscussionUpvoteResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type TypefullyGetConnectionStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/typefully/connection';
};

export type TypefullyGetConnectionStatusErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type TypefullyGetConnectionStatusError = TypefullyGetConnectionStatusErrors[keyof TypefullyGetConnectionStatusErrors];

export type TypefullyGetConnectionStatusResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type TypefullyRemoveApiKeyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/typefully/api-key';
};

export type TypefullyRemoveApiKeyErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type TypefullyRemoveApiKeyError = TypefullyRemoveApiKeyErrors[keyof TypefullyRemoveApiKeyErrors];

export type TypefullyRemoveApiKeyResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type TypefullySetApiKeyData = {
    body: {
        apiKey: string;
    };
    path?: never;
    query?: never;
    url: '/typefully/api-key';
};

export type TypefullySetApiKeyErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type TypefullySetApiKeyError = TypefullySetApiKeyErrors[keyof TypefullySetApiKeyErrors];

export type TypefullySetApiKeyResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type TypefullyGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/typefully/me';
};

export type TypefullyGetMeErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type TypefullyGetMeError = TypefullyGetMeErrors[keyof TypefullyGetMeErrors];

export type TypefullyGetMeResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type TypefullyGetSocialSetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/typefully/social-sets';
};

export type TypefullyGetSocialSetsErrors = {
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type TypefullyGetSocialSetsError = TypefullyGetSocialSetsErrors[keyof TypefullyGetSocialSetsErrors];

export type TypefullyGetSocialSetsResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type TypefullyCreateDraftData = {
    body: {
        socialSetId: string;
        posts: Array<{
            text: string;
            media_ids?: Array<string>;
        }>;
        publishOption?: 'draft' | 'now' | 'next-free-slot';
        scheduledTime?: string;
        draftTitle?: string;
    };
    path?: never;
    query?: never;
    url: '/typefully/draft';
};

export type TypefullyCreateDraftErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type TypefullyCreateDraftError = TypefullyCreateDraftErrors[keyof TypefullyCreateDraftErrors];

export type TypefullyCreateDraftResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type TypefullyUploadMediaData = {
    body: {
        socialSetId: string;
        imageUrl: string;
    };
    path?: never;
    query?: never;
    url: '/typefully/media';
};

export type TypefullyUploadMediaErrors = {
    /**
     * Invalid input data
     */
    400: ErrorBadRequest;
    /**
     * Authorization not provided
     */
    401: ErrorUnauthorized;
    /**
     * Insufficient access
     */
    403: ErrorForbidden;
    /**
     * Internal server error
     */
    500: ErrorInternalServerError;
};

export type TypefullyUploadMediaError = TypefullyUploadMediaErrors[keyof TypefullyUploadMediaErrors];

export type TypefullyUploadMediaResponses = {
    /**
     * Successful response
     */
    200: unknown;
};
